# de um nome
name: Pipeline Robot Framework

# ação que desencadeia a execução
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Projeto de Teste
        uses: actions/checkout@v3
      
      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'