# de um nome
name: Pipeline Robot Framework

# ação que desencadeia a execução
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://franciscoleal.github.io/robot-pipeline/report.html

    steps:
      - name: Projeto de Teste
        uses: actions/checkout@v3
      
      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalação de Depencias do projeto
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Execução dos Testes
        run: |
          robot --outputdir results/ tests/
      
      - name: Salvando resultado dos testes
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: resultado-testes
          path: /results
      
      - name: Configurar Site do relatorio
        uses: actions/configure-pages@v2
        if: always()
        
      - name: Upload do relatorio
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: results/

      - name: Subir site no Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: always()